CREATE TABLE app_user
(
    id          UUID                        NOT NULL,
    name        VARCHAR(255)                NOT NULL,
    email       VARCHAR(255)                NOT NULL,
    password    VARCHAR(255)                NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_verified BOOLEAN                     NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE attachments
(
    id          UUID         NOT NULL,
    filename    VARCHAR(255) NOT NULL,
    description TEXT,
    file_key    VARCHAR(255) NOT NULL,
    capsule_id  UUID,
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE TABLE capsule
(
    id          UUID                        NOT NULL,
    title       VARCHAR(255)                NOT NULL,
    description TEXT,
    status      VARCHAR(255)                NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    open_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    app_user_id UUID,
    CONSTRAINT pk_capsule PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    user_id     UUID                                    NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id UUID NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE verification_token
(
    id      UUID NOT NULL,
    token   UUID NOT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT pk_verificationtoken PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

ALTER TABLE capsule
    ADD CONSTRAINT uc_capsule_title UNIQUE (title);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refreshtoken_token UNIQUE (token);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refreshtoken_user UNIQUE (user_id);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verificationtoken_token UNIQUE (token);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verificationtoken_user UNIQUE (user_id);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_CAPSULE FOREIGN KEY (capsule_id) REFERENCES capsule (id);

ALTER TABLE capsule
    ADD CONSTRAINT FK_CAPSULE_ON_APP_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATIONTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES app_user (id);